create table board(
	id INTEGER NOT NULL AUTO_INCREMENT,
	title TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	FULLTEXT INDEX title(title)
) ENGINE = INNODB DEFAULT CHARSET=utf8;

create table user(
	id INTEGER NOT NULL AUTO_INCREMENT,
	name TEXT,
	password TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	FULLTEXT INDEX name(name)
) ENGINE = INNODB DEFAULT CHARSET=utf8;

create table thread(
	id INTEGER NOT NULL AUTO_INCREMENT,
	board_id INTEGER NOT NULL,
	body TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
) ENGINE = INNODB DEFAULT CHARSET=utf8;
